language: go

go:
  - 1.6
  - 1.7
  - 1.8.x
  - master

os:
  - linux

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go version
  - ./citest.sh

matrix:
  allow_failures:
  - go: master

notifications:
  email:
    on_success: change
    on_failure: always
