language: go

go:
  - 1.6
  - 1.7
  - 1.8.x
  - master

os:
  - linux

services:
  - rabbitmq

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go version
  - make test

env:
  - AMQP_URI=amqp://guest:guest@127.0.0.1:5672/

matrix:
  allow_failures:
  - go: master

notifications:
  email:
    on_success: change
    on_failure: always
